frinyvonnick/gitmoji-changelog

CHANGELOG.md, packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-cli/src/index.js, packages/gitmoji-changelog-core/package.json, packages/gitmoji-changelog-core/src/index.js, packages/gitmoji-changelog-core/src/logger.js, packages/gitmoji-changelog-core/src/metaInfo.js, packages/gitmoji-changelog-core/src/metaInfo.spec.js, packages/gitmoji-changelog-core/src/repoInfo.js, yarn.lock
=> :sparkles: Add logger

packages/gitmoji-changelog-core/src/index.js, packages/gitmoji-changelog-core/src/index.spec.js
=> :sparkles: Sort commits by emoji and date

packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-cli/src/cli.spec.js
And I use the internal logger, this is fancier :)
=> :bug: reduce try/catch scope to print real errors

packages/gitmoji-changelog-core/src/index.js, packages/gitmoji-changelog-core/src/index.spec.js
=> :bug: Remove empty versions

packages/gitmoji-changelog-core/src/parser.js, packages/gitmoji-changelog-core/src/parser.spec.js
=> :bug: Parse unicode emojies in commits

packages/gitmoji-changelog-markdown/package.json, packages/gitmoji-changelog-markdown/src/index.js, packages/gitmoji-changelog-markdown/src/index.spec.js, packages/gitmoji-changelog-markdown/src/template.md, yarn.lock
=> :sparkles: Do not override the top of the existing file

packages/gitmoji-changelog-core/src/groupMapping.js, packages/gitmoji-changelog-core/src/index.js, packages/gitmoji-changelog-core/src/index.spec.js, yarn.lock
=> :sparkles: Filter bookmark commit out

Dockerfile
* passed option --frozen-lockfile to yarn
=> :whale: Do not generate lockfile and fail if update needed

.dockerignore, Dockerfile
=> :whale: optimize context and image size

packages/gitmoji-changelog-cli/package.json, packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-cli/src/index.js, packages/gitmoji-changelog-cli/src/interactiveMode.js, packages/gitmoji-changelog-cli/src/interactiveMode.spec.js, yarn.lock
See #79 
**Interactive option added**
- option name: `--interactive`
- option alias: `-i` 
**Demo** (I don't know why the `gif` frame rate is so slow 😄)
=> :sparkles: Add interactive option to manually select commits

README.md
=> :memo: Add some docker image badges to readme

Dockerfile
* fixed `FROM` image version
* fixed git package version
* inverted `WORKDIR` & `COPY` lines
Fixes #94
=> :whale: fixed dependencies versions in Dockerfile

Dockerfile, README.md
* updated Dockerfile: symlinked binary to user PATH
* added docker usage documentation for local usage & build in readme
* added supported image tag section in readme
=> Need review on the readme modifications, added sections might need to be rearranged 😉 
partly fix #93
=> :memo: doc/add docker usage doc

README.md
=> :pencil: Propose to add badge to our users

packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-core/src/index.js
=> :bug: Fix updating changelog after tagging a version

packages/gitmoji-changelog-core/src/index.js
=> :recycle: Make various changes from review

README.md
I tried to use npx and it works ! 🎉 
I've just updated the README with instructions
=> #110 :sparkles: Add npx instruction on README

.all-contributorsrc, README.md, package.json, yarn.lock
=> :pencil: Add contributors to README

packages/gitmoji-changelog-cli/package.json, packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-cli/src/cli.spec.js, packages/gitmoji-changelog-cli/src/index.js, packages/gitmoji-changelog-cli/src/metaInfo.js, packages/gitmoji-changelog-cli/src/metaInfo.spec.js, packages/gitmoji-changelog-cli/src/presets/node.js, packages/gitmoji-changelog-cli/src/presets/node.spec.js, packages/gitmoji-changelog-cli/src/repository.js, packages/gitmoji-changelog-cli/src/repository.spec.js, yarn.lock
It fixes #85 
@bpetetot a first impression is welcome before going further 👍
=> :sparkles: Use presets to be independent from the package.json

CONTRIBUTING.md, DOCUMENTATION.md, README.md, packages/gitmoji-changelog-cli/src/presets/node.js
I moved some parts of the README in other files
=> :pencil: Improve documentation

.github/workflows/test-and-lint.yml, .travis.yml
=> :construction_worker: setup GitHub CI

.github/workflows/test-and-lint.yml
Fix in order to trigger CI on PR.
Thanks to @kefranabg for the feedback. https://github.com/frinyvonnick/gitmoji-changelog/pull/140#discussion_r345798257
=> :wrench: activate GitHub ci to pull request

.github/workflows/canary-release.yml, DOCUMENTATION.md
=> :contruction_worker: Publish Canary version on master push

packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-markdown/src/index.js
=> :bug: Fix bug preventing generating changelog when previous version doesn't exist

Dockerfile
* Upgrade to node's latest LTS
* Run as user `node`
=> 🐳 Keep Docker image up to date

DOCUMENTATION.md
One of the most glaring examples:
_Previous_
> You didn't the preset you need in the list?
_Updated_
> Didn't see the preset you need in the list?
Additionally various other sentence structure improvements we're made. Hope these help a wider audience grasp the information within this Documentation!
=> Corrected sentence structure

packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-core/src/errors.js, packages/gitmoji-changelog-core/src/index.js
=> :goal_net: Prevent functional errors being catched by issue-reporter

README.md, packages/gitmoji-changelog-documentation/README.md
=> :memo: Change documentation link in README

README.md, packages/gitmoji-changelog-documentation/README.md
Fixes the link so that now it doesn't always refresh the site
=> :memo: Fix the preset link and update year
