packages/gitmoji-changelog-cli/package.json, packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-cli/src/cli.spec.js, yarn.lock
fixes #37 
Note that I didn't found how to cancel promises.
So I put the `process.exit(0)` at the end.
=> :sparkles: Check CLI version

packages/gitmoji-changelog-core/src/groupMapping.js
Just change the group of the `:boom:` gitmoji from `changed` to `breaking_changes`.
Closes #57
=> :sparkles: Add a breaking changes section

packages/gitmoji-changelog-markdown/src/index.js, packages/gitmoji-changelog-markdown/src/index.spec.js
=> :bug: fix duplication with incremental update

packages/gitmoji-changelog-cli/src/index.js, packages/gitmoji-changelog-core/src/index.js, packages/gitmoji-changelog-core/src/index.spec.js, packages/gitmoji-changelog-core/src/parser.js, packages/gitmoji-changelog-core/src/parser.spec.js, packages/gitmoji-changelog-markdown/src/index.js, packages/gitmoji-changelog-markdown/src/index.spec.js, packages/gitmoji-changelog-markdown/src/template.md
Closes #55 
>  In git commits we have the "author fullname" and "author email" but we can't have the github/gitlab... username
Keep it in that way but add an option to cli to add or not the author in the changelog. Because in some project when only one person work on it, he may not want to have the same author on each line (it doesnt bring value to the changelog)
So I propose to have the following option to activate it:
```bash
gitmoji-changelog --with-author
```
=> :sparkles: Add the author in changelog lines

Dockerfile
I had 2 options to write this Dockerfile:
1. Build the `gitmoji-changelog` "binary" from source
1. Install the binary from npm registry
Even if the second option offers a lighter Docker Image (102MB) compared to the first one (263MB), I chose the first one because I think we cannot build a Docker Image based on "binary" from "https://registry.npmjs.org/gitmoji-changelog" until it is available (but I maybe wrong, just tell me).
So, this Dockerfile:
- copy sources of `gitmoji-changelog`
- then build them by using `yarn`
- and define the entrypoint to `/usr/src/gitmoji-changelog/node_modules/.bin/gitmoji-changelog`
`docker run --rm -v $(pwd):/usr/src/app gitmoji-changelog` where `$(pwd)` is the folder of the project you want to generate the CHANGELOG.md.
All Commands, Positionals and Options …
=> :whale: Init dockerfile

packages/gitmoji-changelog-markdown/package.json, yarn.lock
Upgrade handlebar dependency because of https://www.npmjs.com/advisories/755
This time with updated yarn.lock :)
=> update handlebar to 4.0.14

Dockerfile, README.md
Fix #106 
* after some experimentation, mutli-stage build is definitely not an option with Node.js
* fixed the workdir (`/app`) where gitmoji-changelog expect the code to be inside the container
* updated docker image usage according to the modifications
=> :whale: small Dockerfile improvment and updated docker image usage

packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-markdown/src/index.js
I had an issue where pre-release tag were detected as latest version.
=> :bug: Handle pre-release as latest version in markdown

packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-cli/src/cli.spec.js, packages/gitmoji-changelog-cli/src/metaInfo.spec.js, packages/gitmoji-changelog-core/src/index.js, packages/gitmoji-changelog-core/src/index.spec.js
I made a first separation using a prefixed function with `_` so we can discuss about it. @bpetetot I think the logic that remains in `generateChangelog` function should be moved to `cli` package. What 
do you think of it?
The diff also let me think we could get rid of `meta` from `core` package.
=> :recycle: Change core function parameters from "mode" to "from" and "to"

packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-cli/src/cli.js
Fix #159 
If the preset could not find configuration it displays:
```
Cannot retrieve configuration for preset [preset name].
```
If the preset did not return the version it displays:
```
Cannot retrieve the version from your configuration. Check it or you can do "gitmoji-changelog <wanted version>".
```
=> :recycle: Improve error messages from preset system

packages/gitmoji-changelog-cli/package.json, packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-core/src/index.js, packages/gitmoji-changelog-core/src/index.spec.js, packages/gitmoji-changelog-core/src/parser.js, packages/gitmoji-changelog-core/src/parser.spec.js, yarn.lock
=> :sparkles: Add configuration so users can customize commit mapping

packages/gitmoji-changelog-cli/src/presets/generic.js, packages/gitmoji-changelog-cli/src/presets/generic.spec.js
Fix #157 
It uses a configuration file at project root called `.gitmoji-changelogrc` containing the following mandatory properties.
```json
{
"project": {
"name": "yvonnickfrin.dev",
"description": "My blog",
"version": "1.1.0"
}
}
```
Should it be the default preset @bpetetot?
=> :sparkles: Add a generic preset that uses a configuration file

DOCUMENTATION.md, README.md
It adds documentation about generic preset. I wondering if we should create a specific documentation file about preset. Maybe we should add it with the next preset.
=> :pencil: Add documentation about generic preset

packages/gitmoji-changelog-core/src/fromGitFile.js, packages/gitmoji-changelog-core/src/index.js, packages/gitmoji-changelog-core/src/parser.js, packages/gitmoji-changelog-core/src/parser.spec.js
In order to use gitmoji-changlelog with other git clients (like a http client or other), we need to extract the dependency with the current git client (reading .git on the filesystem).
Here is a naive refactoring extracting all calls done by the current git client.
First step for #168
You can now call the core with:
```
generateChangelog(from, to, { client: myGitClient }) 
```
The client `myGitClient` must have 2 functions:
```
getTags() : Promise([string])
getCommits(fromTag: string, toTag: string) : Promise([{ hash, author, date, subject, body }])
```
=> :recycle: make core independent from the git client.

packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-cli/src/cli.js
=> :bug: Fix a bug when version is missing in configuration but passed as argument

packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-cli/src/index.js
It adds a default value for the release option in the init command.
Closes #188 #182
=> :bug: Fix init command

packages/gitmoji-changelog-cli/package.json, packages/gitmoji-changelog-cli/src/index.js, packages/gitmoji-changelog-cli/src/presets/helm.js, packages/gitmoji-changelog-cli/src/presets/helm.spec.js, packages/gitmoji-changelog-documentation/README.md, yarn.lock
Hi there 👋
I'm working on some Helm packages these times, and I figured that a Helm preset could be useful instead of maintaining a separate `.gitmoji-changelogrc` file.
So here is a PR implementing this :tada:
=> ✨ Add Helm preset

.github/workflows/canary-release.yml, .github/workflows/test-and-lint.yml, package.json, packages/gitmoji-changelog-cli/package.json, packages/gitmoji-changelog-core/package.json, packages/gitmoji-changelog-markdown/package.json, yarn.lock
Upgrade these packages to fix their vulnerabilities
* `lerna` => v4
* `libnpm` => 3.0.1 (sadly it's last published version and still have some moderate vulnerabilities in nested packages 😞)
* `jest` => v26
* `git-semver-tags` => v4
* `yargs` => v17
Remove unusued `get-pkg-repo` dependency
Upgrade Node.js used in CI workflows to v12. According to [Node.js release chart](https://nodejs.org/en/about/releases/), v10 is not maintained anymore thus it's possibly vulnerable.
Relates #209
=> ⬆️ Upgrade vulnerable packages

packages/gitmoji-changelog-documentation/README.md
This PR contains documentation update. "helm" is missing at list of available presets section.
=> 📝 Add helm to list of available presets section

packages/gitmoji-changelog-cli/src/index.js, packages/gitmoji-changelog-cli/src/presets/python.js, packages/gitmoji-changelog-cli/src/presets/python.spec.js, packages/gitmoji-changelog-documentation/README.md
Adds the `python` preset to generate the gitmoji-changelog.
This should cover any python package that follows [PEP621](https://peps.python.org/pep-0621/), and it also covers poetry's distinct metadata section (I am unaware of other distinctions but they should also be covered by this).
=> ✨ Added python preset

packages/gitmoji-changelog-cli/src/cli.e2e.js, packages/gitmoji-changelog-cli/src/cli.js, packages/gitmoji-changelog-core/src/index.js
This PR fixes issue #231. Node 14 doesn't seem to accept `undefined` as `data` arg to `fs.writeFileSync()`, so let's just pass an empty string.
Moreover, the last E2E test (_"generate changelog > update > should display an error if requested version isn't semver"_) expects an error to be logged when passed a non-semver `release` option. However the CLI throws a generic `Error` in these cases, which are eventually intercepted by the issue reporter instead of being logged: 
https://github.com/fredericbonnet/gitmoji-changelog/blob/4a293caece43a953940ed7d753387c41f5df33ab/packages/gitmoji-changelog-cli/src/cli.js#L105-L128
I don't think that's the intended behavior, so the fix is to throw a `FunctionalError` instead.
Happy Hacktoberfest! 🎃
=> 🐛 Fix E2E tests and semver validation error type
